#!/usr/bin/env zsh
#
#████████████████████████████████████████████████████████████████████████████
#
#
#        █████╗ ██╗     ██╗ █████╗ ███████╗███████╗███████╗
#       ██╔══██╗██║     ██║██╔══██╗██╔════╝██╔════╝██╔════╝
#       ███████║██║     ██║███████║███████╗█████╗  ███████╗
#       ██╔══██║██║     ██║██╔══██║╚════██║██╔══╝  ╚════██║
#       ██║  ██║███████╗██║██║  ██║███████║███████╗███████║
#       ╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
#    
#       GitHub:  https://github.com/fcarvalhopacheco
#
#                                                      
#████████████████████████████████████████████████████████████████████████████

#  Vim
alias vi="nvim"
alias vim="nvim"


#  Edit files
alias aedit=" $EDITOR $ZDOTDIR/zshaliases; source $ZDOTDIR/zshaliases"
alias zedit=" $EDITOR $ZDOTDIR/.zshrc; source $ZDOTDIR/.zshrc"

#  Copy
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

#  Read Disk
alias df='df -h'     # human-readable sizes

#  Navigation
alias ..="cd .."
alias ...="cd ../.."
alias cl=clear
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index
#  LS
# alias lad='ls -d -- .*(/)'				# only show dot-directoriesalias
# alias lsa='ls -a -- .*(.)'				# only show dot-filesalias
# alias ls="ls"
# alias l="ls -la"
# alias ll="ls -l"
# alias ltra="ls -ltra"

## --git LETTERS
# M: Modified - The file has been modified but not yet staged.
# N: New - A new file that has not been added to the repository yet.
# I: Ignored - The file is ignored by Git, typically as defined in .gitignore.
# Other Statuses:
# D: Deleted - The file is deleted from the working directory but not yet staged.
# R: Renamed - The file has been renamed.
# T: Type-change - The type of the file changed (e.g., from regular file to symlink).
# U: Conflicted - The file is in a state of conflict due to merge or rebase.


# Enhanced eza aliases with sort by modification time

# List Directories Only, with Custom Time Style
alias l="eza -l --icons --git -a"
alias ld="eza -lD --icons --color=always --group --git --sort=modified --time-style=+'%Y %b %d %H:%M'"
# List Files Only, Excluding Directories, with Custom Time Style
alias lf="eza -lF --icons --color=always --group --git --sort=modified --time-style=+'%Y %b %d %H:%M'| grep -v /"
# List Hidden Files and Directories, Prioritizing Directories, with Custom Time Style
alias lh="eza -dl .* --group-directories-first --icons --color=always --group --git --sort=modified --time-style=+'%Y %b %d %H:%M'"
# List All Files and Directories, Prioritizing Directories, with Custom Time Style
alias ll="eza -al --group-directories-first --icons --color=always --git --sort=modified --time-style=+'%Y %b %d %H:%M'"
alias lt="eza -al --icons --color=always --group --git --sort=modified --time-style=+'%Y %b %d %H:%M'"


#  Shortcuts
alias docs="cd ~/Documents"
alias dl="cd ~/Downloads/"
alias dw="cd ~/Documents/workspace/"
alias dwg="cd ~/Documents/workspace/1.git/"
alias dot="cd ~/.dotfiles/"


# Git 
alias gs='git status'
alias gss='git status -s'
alias gc='git commit -S -m'
alias gd='git diff'

# Conda
alias condaon="source ~/.config/zsh/zshconda && echo 'conda is now on' && source $ZDOTDIR/.zshrc"

# Newsboat
alias nb='newsboat'

# Nvim
#alias note='nvim +"ObsidianNew test"'
#alias todo='nvim +"Telekasten goto_today"'

# Taskwarrior
alias taskadd="zsh $HOME/.dotfiles/scripts/.config/scripts/zsh/taskadd.sh"
