#!/usr/bin/env zsh
#
#████████████████████████████████████████████████████████████████████████████
#
#
#       ██████╗ ██╗███╗   ██╗██████╗ ██╗███╗   ██╗ ██████╗ ███████╗
#       ██╔══██╗██║████╗  ██║██╔══██╗██║████╗  ██║██╔════╝ ██╔════╝
#       ██████╔╝██║██╔██╗ ██║██║  ██║██║██╔██╗ ██║██║  ███╗███████╗
#       ██╔══██╗██║██║╚██╗██║██║  ██║██║██║╚██╗██║██║   ██║╚════██║
#       ██████╔╝██║██║ ╚████║██████╔╝██║██║ ╚████║╚██████╔╝███████║
#       ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝
#
#             GitHub:  https://github.com/fcarvalhopacheco
#
#
#    References:
#       - https://www.strcat.de/dotfiles/
#       - https://github.com/Phantas0s/.dotfiles/blob/master/zsh/completion.zsh
#
#
#    This script is based on code from https://github.com/zap-zsh/vim, 
#    which is licensed under the GNU GPL v3.0. The original code can be 
#    found at:  https://github.com/zap-zsh/vim/blob/master/vim.plugin.zsh
#   
#
#████████████████████████████████████████████████████████████████████████████


# Enable vi mode key bindings
bindkey -v

# Set KEYTIMEOUT to 1 second for faster key recognition
export KEYTIMEOUT=1

# Bind 'v' in vicmd mode to edit-command-line (use Vim to edit current command line)
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Bind CTRL-v to edit-command-line (use Vim to edit current command line)
bindkey -v '^v' edit-command-line

# Configure hjkl navigation during completion menu selection
if [[ -o menucomplete ]]; then
    bindkey -M menuselect 'h' vi-backward-char
    bindkey -M menuselect 'k' vi-up-line-or-history
    bindkey -M menuselect 'j' vi-down-line-or-history
    bindkey -M menuselect 'l' vi-forward-char
    bindkey -M menuselect 'i' accept-and-menu-complete
    bindkey -M menuselect 'o' accept-and-infer-next-history
    bindkey -M menuselect '^d' clear-screen
    bindkey -M menuselect 'u' undo
fi
