#!/usr/bin/env zsh
#
#████████████████████████████████████████████████████████████████████████████
#
#
#       ██████╗ ██╗███╗   ██╗██████╗ ██╗███╗   ██╗ ██████╗ ███████╗
#       ██╔══██╗██║████╗  ██║██╔══██╗██║████╗  ██║██╔════╝ ██╔════╝
#       ██████╔╝██║██╔██╗ ██║██║  ██║██║██╔██╗ ██║██║  ███╗███████╗
#       ██╔══██╗██║██║╚██╗██║██║  ██║██║██║╚██╗██║██║   ██║╚════██║
#       ██████╔╝██║██║ ╚████║██████╔╝██║██║ ╚████║╚██████╔╝███████║
#       ╚═════╝ ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝
#
#             GitHub:  https://github.com/fcarvalhopacheco
#
#
#    References:
#       - https://www.strcat.de/dotfiles/
#       - https://github.com/Phantas0s/.dotfiles/blob/master/zsh/completion.zsh
#       - https://thevaluable.dev/zsh-line-editor-configuration-mouseless/
#
#
#    This script is based on code from https://github.com/zap-zsh/vim, 
#    which is licensed under the GNU GPL v3.0. The original code can be 
#    found at:  https://github.com/zap-zsh/vim/blob/master/vim.plugin.zsh
#   
#
#████████████████████████████████████████████████████████████████████████████


# Enable vi mode key bindings
# A keymap is a set of keystrokes executing ZLE widgets. For each keymap, 
# the mapping of keystrokes to widgets can be completely different.
#
# For example, if we want to bind CTRL+h to the series of keystrokes CTRL+L 
# (which clear the screen by default) and then writes “hello”: 
#     ```sh 
#     bindkey -s '^h' '^l hello' 
#     ```

# Activate 
bindkey -v

# Set KEYTIMEOUT to 1 second for faster key recognition
export KEYTIMEOUT=1

# Bind 'v' in vicmd mode to edit-command-line (use Vim to edit current command line)
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Bind CTRL-v to edit-command-line (use Vim to edit current command line)
bindkey -v '^v' edit-command-line

# Configure hjkl navigation during completion menu selection
if [[ -o menucomplete ]]; then
    bindkey -M menuselect 'h' vi-backward-char
    bindkey -M menuselect 'k' vi-up-line-or-history
    bindkey -M menuselect 'j' vi-down-line-or-history
    bindkey -M menuselect 'l' vi-forward-char
    bindkey -M menuselect 'i' accept-and-menu-complete
    bindkey -M menuselect 'o' accept-and-infer-next-history
    bindkey -M menuselect '^d' clear-screen
    bindkey -M menuselect 'u' undo
fi


# Check: https://thevaluable.dev/zsh-install-configure-mouseless/#adding-text-objects
# Load the select-bracketed and select-quoted widgets
autoload -Uz select-bracketed select-quoted

# Define the select-quoted widget
zle -N select-quoted

# Define the select-bracketed widget
zle -N select-bracketed

# Set up key bindings for the viopp and visual keymaps
for km in viopp visual; do
  # Bind the '-' key to the 'vi-up-line-or-history' function
  bindkey -M $km -- '-' vi-up-line-or-history

  # Bind select-quoted to the specified keys
  for c in {a,i}${(s..)^:-\'\"\`\|,./:;=+@}; do
    bindkey -M $km $c select-quoted
  done

  # Bind select-bracketed to the specified keys
  for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
    bindkey -M $km $c select-bracketed
  done
done



