#!/usr/bin/env zsh

typeset -g ZSH_ROOT="${ZDOTDIR:-$HOME/.config/zsh}"
source "$ZSH_ROOT/lib/source.zsh"
_zsh_source "lib/plugins.zsh"
_zsh_source "conf.d/35-plugins.zsh"
_zsh_source "conf.d/41-completion.zsh"
