#!/usr/bin/env zsh
# zmodload zsh/zprof

#
#████████████████████████████████████████████████████████████████████████████
#
#
#      ██████╗ ██████╗  ██████╗ ███╗   ███╗██████╗ ████████╗
#      ██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝
#      ██████╔╝██████╔╝██║   ██║██╔████╔██║██████╔╝   ██║   
#      ██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██╔═══╝    ██║   
#      ██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║        ██║   
#      ╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝        ╚═╝   
#
#        GitHub:  https://github.com/fcarvalhopacheco
#                                                           
#   References:
#       - https://zsh-prompt-generator.site
#       - https://dev.to/cassidoo/customizing-my-zsh-prompt-3417
#       - Colors: https://github.com/zsh-users/zsh/blob/master/Functions/Misc/colors
#       - Symbols: https://symbl.cc/en/
#       - vcs_info : https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
#
#
#   *This script is based on code from https://github.com/zap-zsh, 
#   which is licensed under the GNU GPL v3.0. The original code can be 
#   found at: https://github.com/zap-zsh/atmachine-prompt/blob/master/atmachine-prompt.zsh-theme 
#
#████████████████████████████████████████████████████████████████████████████

# Loadthe Version Control System into your prompt
# autoload -Uz vcs_info
# autoload -U colors && colors
#
# zstyle ':vcs_info:*' enable git 
#
# precmd_vcs_info() { vcs_info }
# precmd_functions+=( precmd_vcs_info )
# setopt prompt_subst
#
# zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# # 
# +vi-git-untracked(){
#     if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
#         git status --porcelain | grep '??' &> /dev/null ; then
#         hook_com[staged]+='!' # NEWFILES
#     fi
# }
#
# ##############################################################################
# # %s : The current version control system, like git or svn.
# # %r : The name of the root directory of the repository
# # %S : The current path relative to the repository root directory
# # %b : Branch information, like master
# # %m : In case of Git, show information about stashes
# # %u : Show unstaged changes in the repository
# # %c : Show staged changes in the repository
# ##############################################################################
# zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[magenta]%} %b%{$fg[green]%})"
#
# PROMPT="%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[yellow]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}🏄 :%{$fg_bold[magenta]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}"
# PROMPT+="\$vcs_info_msg_0_ "
# #zprof
#

#Set prompt options
#source /Users/fcp/.dotfiles/zsh/.config/zsh/scripts/git-prompt.sh
# setopt prompt_subst
# autoload -U colors && colors
#
# # Git prompt customization
# GIT_PS1_SHOWDIRTYSTATE=1
# GIT_PS1_SHOWSTASHSTATE=1
# GIT_PS1_SHOWUNTRACKEDFILES=1
# GIT_PS1_SHOWUPSTREAM="auto"
# GIT_PS1_SHOWCOLORHINTS=1
#
# # # # Define the precmd function
# precmd() {
#     __git_ps1 "%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[yellow]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}🏄 :%{$fg_bold[magenta]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}" " %B%{$reset_color%}" " (%s)"
# }



# Enable prompt substitution and load colors
# setopt prompt_subst
# autoload -U colors && colors
#
# # Git prompt customization
# GIT_PS1_SHOWDIRTYSTATE=1
# GIT_PS1_SHOWSTASHSTATE=1
# GIT_PS1_SHOWUNTRACKEDFILES=1
# GIT_PS1_SHOWUPSTREAM="auto"
# GIT_PS1_SHOWCOLORHINTS=1
#
# # Define the precmd function
# precmd() {
#     # Avoid complex processing if not in a git directory
#     if git rev-parse --git-dir > /dev/null 2>&1; then
#         __git_ps1 "%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[yellow]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}🏄 :%{$fg_bold[magenta]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}" " %B%{$reset_color%}" " (%s)"
#     else
#         # Simpler prompt outside git directories
#         print -P "%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[yellow]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}🏄 :%{$fg_bold[magenta]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}"
#     fi
# }

# Enable prompt substitution and load colors
setopt prompt_subst
autoload -U colors && colors

# Git prompt customization
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS=1

# Load git-prompt
source /Users/fcp/.dotfiles/zsh/.config/zsh/scripts/git-prompt.sh

# Define the prompt symbol based on the last command's success
prompt_symbol() {
    if [[ $? -eq 0 ]]; then
        echo "%{$fg_bold[cyan]%}✔︎"
    else
        echo "%{$fg_bold[orange]%}✖︎"
    fi
}

# Define the precmd function
precmd() {
    local ps_symbol=$(prompt_symbol)
    local user_host="%{$fg_bold[purple]%}%n%{$fg_no_bold[green]%}@%m"
    local current_dir="%{$fg_bold[blue]%}%~"
    local git_info=''

    # Check if in a git directory and fetch status
    if git rev-parse --git-dir > /dev/null 2>&1; then
        git_info=$(__git_ps1 " %s")
        # Custom replacements for git status symbols
        git_info=${git_info//\*/%{$fg_bold[red]%}✘}     # Dirty state
        git_info=${git_info//+/%{$fg_bold[yellow]%}⚑}   # Added files
        git_info=${git_info//=/%{$fg_bold[green]%}✓}    # Ahead of remote
        git_info=${git_info//>/%{$fg_bold[blue]%}▶︎}    # Staged changes
    fi

    # Constructing the prompt
    PS1="${user_host} ${ps_symbol} ${current_dir} [${git_info}] %{$reset_color%} "
}

# Apply the new prompt
precmd

